baseURL = 'https://radiant-travesseiro-30bf7c.netlify.app/'
languageCode = 'en-us'
title = 'Tai Alt'
theme = 'nostyleplease'

# show HTML 
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
    [markup.goldmark.renderer]
      unsafe = true
